export const allAmenities = [
  { "amenity_id": 1,  "amenity": "TV" },
  { "amenity_id": 2,  "amenity": "Cable TV" },
  { "amenity_id": 3,  "amenity": "Internet" },
  { "amenity_id": 4,  "amenity": "Wifi" },
  { "amenity_id": 5,  "amenity": "Air conditioning" },
  { "amenity_id": 6,  "amenity": "Wheelchair accessible" },
  { "amenity_id": 7,  "amenity": "Pool" },
  { "amenity_id": 8,  "amenity": "Kitchen" },
  { "amenity_id": 9,  "amenity": "Free parking on premises" },
  { "amenity_id": 10, "amenity": "Paid parking off premises" },
  { "amenity_id": 11, "amenity": "Smoking allowed" },
  { "amenity_id": 12, "amenity": "Pets allowed" },
  { "amenity_id": 14, "amenity": "Doorman" },
  { "amenity_id": 15, "amenity": "Gym" },
  { "amenity_id": 16, "amenity": "Breakfast" },
  { "amenity_id": 17, "amenity": "Pets live on this property" },
  { "amenity_id": 18, "amenity": "Dog(s)" },
  { "amenity_id": 19, "amenity": "Cat(s)" },
  { "amenity_id": 20, "amenity": "Other pet(s)" },
  { "amenity_id": 21, "amenity": "Elevator" },
  { "amenity_id": 22, "amenity": "Garage parking" },
  { "amenity_id": 23, "amenity": "Free street parking" },
  { "amenity_id": 25, "amenity": "Hot tub" },
  { "amenity_id": 27, "amenity": "Indoor fireplace" },
  { "amenity_id": 28, "amenity": "Buzzer/wireless intercom" },
  { "amenity_id": 30, "amenity": "Heating" },
  { "amenity_id": 31, "amenity": "Family/kid friendly" },
  { "amenity_id": 32, "amenity": "Suitable for events" },
  { "amenity_id": 33, "amenity": "Washer" },
  { "amenity_id": 34, "amenity": "Dryer" },
  { "amenity_id": 35, "amenity": "Smoke alarm" },
  { "amenity_id": 36, "amenity": "Carbon monoxide alarm" },
  { "amenity_id": 37, "amenity": "First aid kit" },
  { "amenity_id": 38, "amenity": "Safety card" },
  { "amenity_id": 39, "amenity": "Fire extinguisher" },
  { "amenity_id": 40, "amenity": "Essentials" },
  { "amenity_id": 41, "amenity": "Shampoo" },
  { "amenity_id": 42, "amenity": "Lock on bedroom door" },
  { "amenity_id": 43, "amenity": "24‑hour check‑in" },
  { "amenity_id": 44, "amenity": "Hangers" },
  { "amenity_id": 45, "amenity": "Hair dryer" },
  { "amenity_id": 46, "amenity": "Iron" },
  { "amenity_id": 47, "amenity": "Laptop‑friendly workspace" },
  { "amenity_id": 49, "amenity": "translation missing: en.hosting_amenity_49" },
  { "amenity_id": 50, "amenity": "translation missing: en.hosting_amenity_50" },
  { "amenity_id": 51, "amenity": "Self check‑in" },
  { "amenity_id": 52, "amenity": "Smart lock" },
  { "amenity_id": 53, "amenity": "Keypad" },
  { "amenity_id": 54, "amenity": "Lockbox" },
  { "amenity_id": 55, "amenity": "Building staff" }
]
